<div class="col-sm-12">
    <table class="table">
        <thead>
            <tr>
                <th><h2>Dados do Cliente</h2></th>
            </tr>
        </thead>
    </table>
</div>

<form class="form-group" action="/pedido/finalizar/" method="post">
	<div class="col-sm-12">
	    <div class="col-sm-6">
	  		<div class="form-group">
	    		<label for="nome">Nome</label>
	    		<input type="text" name="cliente[nome]" class="form-control" id="nome" placeholder="Digite seu nome completo" required maxlength="45">
	  		</div>
	    </div>
		<div class="col-sm-6">    		
	  		<div class="form-group">
	    		<label for="email">Email</label>
	    		<input type="email" name="cliente[email]" class="form-control" id="email" placeholder="Digite seu email" required maxlength="45">
	  		</div>
	  	</div>
	  	<div class="col-sm-6">
	  		<div class="form-group">
	    		<label for="cpf">CPF</label>
	    		<input type="text" name="cliente[cpf]" class="form-control" id="cpf" placeholder="Digite seu CPF" pattern="[0-9]+$" required maxlength="11">
	  		</div>
	  	</div>
	  	<div class="col-sm-6">
	  		<div class="form-group">
	    		<label for="data_nascimento">Data de Nascimento</label>
	    		<input type="date" name="cliente[data_nascimento]" class="form-control" id="data_nascimento" placeholder="Digite sua data de nascimento" required>
	  		</div>
	  	</div>  	
	  	<div class="col-sm-6">
	 		<div class="form-group">
	    		<label for="telefone">Telefone</label>
	    		<input type="tel" name="cliente[telefone]" class="form-control" id="telefone" placeholder="Digite um telefone para contato" required maxlength="11">
	  		</div>
	  	</div>  	
	</div>

	<div class="col-sm-12">
	    <table class="table">
	        <thead>
	            <tr>
	                <th><h2>Endereço de Envio</h2></th>
	            </tr>
	        </thead>
	    </table>
	</div>

	<div class="col-sm-12">
	    <div class="col-sm-6">
	  		<div class="form-group">
	    		<label for="logradouro">Logradouro</label>
	    		<input type="logradouro" name="endereco[logradouro]" class="form-control" id="logradouro" placeholder="Digite o logradouro" required maxlength="100">
	  		</div>
	    </div>
		<div class="col-sm-6">    		
	  		<div class="form-group">
	    		<label for="numero">Numero</label>
	    		<input type="number" name="endereco[numero]" class="form-control" id="numero" placeholder="Digite o numero" pattern="[0-9]+$">
	  		</div>
	  	</div>
	  	<div class="col-sm-6">
	  		<div class="form-group">
	    		<label for="complemento">Complemento</label>
	    		<input type="text" name="endereco[complemento]" class="form-control" id="complemento" placeholder="Digite o Complemento">
	  		</div>
	  	</div>
	  	<div class="col-sm-6">
	  		<div class="form-group">
	    		<label for="cep">CEP</label>
	    		<input type="number" name="endereco[cep]" class="form-control" id="cep" placeholder="Digite o CEP" pattern="[0-9]+$" min="1" max="99999999">
	  		</div>
	  	</div>  	
	  	<div class="col-sm-6">
	 		<div class="form-group">
	    		<label for="bairro">Bairro</label>
	    		<input type="text" name="endereco[bairro]" class="form-control" id="bairro" placeholder="Digite o bairro" required maxlength="100">
	  		</div>
	  	</div> 
	  	<div class="col-sm-6">
	 		<div class="form-group">
	    		<label for="cidade">Cidade</label>
	    		<input type="text" name="endereco[cidade]" class="form-control" id="cidade" placeholder="Digite a cidade" required maxlength="100">
	  		</div>
	  	</div>
	  	<div class="col-sm-6">
	 		<div class="form-group">
	    		<label for="estado">Estado</label>
	    		<input type="text" name="endereco[estado]" class="form-control" id="estado" placeholder="Digite o Estado" required maxlength="50">
	  		</div>
	  	</div>  	  		  		
	  	<br>
	</div>

	<div class="col-sm-12">
	    <table class="table">
	        <thead>
	            <tr>
	                <th><h2>Dados de Pagamento</h2></th>
	            </tr>
	        </thead>
	    </table>
	</div>

	<div class="col-sm-6">
		<select class="form-control" name="forma_pagamento_id">
	  		<option value="1">Boleto</option>
	  		<option value="2">Cartão de Crédito</option>
	  		<option value="3">Débito</option>
		</select>
	</div>
  	<div class="row">
		<input type="submit" class="btn btn-success">
	</div>
</form>