<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th><h2>Categorias</h2></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->categorias as $categoria): ?>
                <tr>
                    <td>
                        <a href="/categoria/<?php echo $categoria['categoria_id'] ?>/produtos/">
                            <?php echo $categoria['descricao'] ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>