<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th><h2>Categorias</h2></th>
            </tr>
        </thead>
    </table>
</div>
<div class="container">
    <?php foreach ($this->categorias as $categoria) : ?>
        <div class="row">
            <div class="col-md-2">
                <a href="/categoria/<?php echo $categoria['categoria_id'] ?>/produtos/">
                    <p><h5><?php echo $categoria['descricao'] ?></h5></p>
                </a>
            </div>
        </div>
    <?php endforeach; ?>    
</div>