<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th><h2>Categorias</h2></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->categorias as $categoria): ?>
                <tr>
                    <td><?php echo $categoria['descricao'] ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>